### ISSUE TITLE
BUILD ISSUE - BACON

### ISSUE THREAD

**Issue by drtikv** [AOSPlusone/platform_build#1]
Build comes up unsucessful at

New untouched repo sync, of course:

[  4% 1500/36352] -e Building Kernel Config
FAILED: /bin/bash -c "(make -j6  -C kernel/oneplus/msm8974 O=out/target/product/bacon/obj/KERNEL_OBJ ARCH=arm CROSS_COMPILE=\"/home/drtikv1/prebuilts/misc/linux-x86/ccache/ccache arm-linux-androideabi-\" VARIANT_DEFCONFIG= SELINUX_DEFCONFIG= bacon_defconfig ) && (if [ ! -z \"\" ]; then 			echo \"Overriding kernel config with ''\"; 			echo  >> out/target/product/bacon/obj/KERNEL_OBJ/.config; 			make -j6 -C kernel/oneplus/msm8974 O=out/target/product/bacon/obj/KERNEL_OBJ ARCH=arm CROSS_COMPILE=\"/home/drtikv1/prebuilts/misc/linux-x86/ccache/ccache arm-linux-androideabi-\" oldconfig; fi ) && (if [ ! -z \"\" ]; then 			echo \"Using additional config ''\"; 			kernel/oneplus/msm8974/scripts/kconfig/merge_config.sh -m -O out/target/product/bacon/obj/KERNEL_OBJ out/target/product/bacon/obj/KERNEL_OBJ/.config kernel/oneplus/msm8974/arch/arm/configs/; 			make -j6 -C kernel/oneplus/msm8974 O=out/target/product/bacon/obj/KERNEL_OBJ ARCH=arm CROSS_COMPILE=\"/home/drtikv1/prebuilts/misc/linux-x86/ccache/ccache arm-linux-androideabi-\" KCONFIG_ALLCONFIG=out/target/product/bacon/obj/KERNEL_OBJ/.config alldefconfig; fi )"
make: Entering directory '/home/drtikv1/kernel/oneplus/msm8974'
/bin/sh: 1: cd: can't cd to out/target/product/bacon/obj/KERNEL_OBJ
Makefile:121: *** output directory "out/target/product/bacon/obj/KERNEL_OBJ" does not exist.  Stop.
make: Leaving directory '/home/drtikv1/kernel/oneplus/msm8974'

**Comment by freshgiammi** [comment]
I'll eventually fix this, you can workaround it by setting a different out directory.

export OUT_DIR="/patch/to/out/dir/"

**Comment by freshgiammi** [comment]
AOSPlusone/android_kernel_oneplus_msm8974@cc28b6e18d6d4af09e0c251c83cf16edced255cd

Fixes this issue.
